DELETE http://localhost:3003/api/blogs/664de7e00e51b963c18f0d87

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
      "title": "Type wars",
      "author": "Robert C. Martin",
      "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
      "likes": 2,
      "user": "665058ae84a9b7a714536d0c"
}


###

POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
      "username": "eee",
      "name": "Superuser2",
      "password": "eee"
}

###

POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
      "username": "eee",
      "password": "eee"
}