POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Sueños de acero y neon",
    "author": "Jordi Wild",
    "url": "https://www.casadellibro.com/libro-suenos-de-acero-y-neon/9788427042353/2744729"
}

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "jordiwild",
    "name": "Jorge Salvaje"
}

###

PUT http://localhost:3003/api/users/jordimfukingwild HTTP/1.1
Content-Type: application/json

{
    "username": "jordiwild"
}

