services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bloglist
    volumes:
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data/mongo_data:/data/db

  backend:
    image: bloglist-backend-prod
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile

  frontend:
    image: bloglist-frontend-prod
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:800
    container_name: nginxRP
    depends_on:
      - frontend
      - backend